### ISSUE TITLE
Can't change size of PC/NPC

### ISSUE THREAD

**Issue by tsansom** [ocangelo/roll20#5]
Any time I try to change the size of either the PC or NPC, the script errors out with:
```
TypeError: Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at handleGraphicMovement (apiscript.js:9500:28)
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:154:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:154:1), <anonymous>:70:8)
    at TrackedObj.set (/home/node/d20-api-server/api.js:1048:14)
    at updateLocalCache (/home/node/d20-api-server/api.js:1346:18)
    at /home/node/d20-api-server/api.js:1530:11
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560
    at hc (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:39:147)
    at Kd (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:546)
    at Id.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:489)
```

**Comment by ocangelo** [comment]
i sorry i missed this comment completely, fixed a bug related to this a while ago, let me know if you still have issues with the latest version (just open a new issue)
